### ISSUE TITLE
Ошибка компилятор ассемблера

### ISSUE THREAD

**Issue by ilovegithub-coder** [xi816/gc16x#1]
при компиляции кода возникла ошибка
Traceback (most recent call last):
  File "/home/user/GoidaOS/asm/asm.py", line 728, in <module>
    sys.exit(main(len(sys.argv), sys.argv));
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/GoidaOS/asm/asm.py", line 721, in main
    c, exitcode = CompileGC16X(tokens, FetchLabels(tokens));
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/GoidaOS/asm/asm.py", line 197, in CompileGC16X
    while (prog[pos][0] != T_EOF):
           ~~~~^^^^^
IndexError: list index out of range

**Comment by xi816** [comment]
ассембли код покажи

**Comment by ilovegithub-coder** [comment]
jmp boot

; GovnFS signature bytes that are not allowed in code:
; F0, F1, F2, F7
; F0 -- Directory block
; F1 -- File block
; F2 -- Group block
; F7 -- Disk end
;
; Dir: F0 [name] F0
; File: F1 [filename] F2 [dir] F2 [contents] F1

puts:
  ldd %s     ; G = S
  lodsb      ; S = [S]
  push %s    ; PUSH(S)
  int $02    ; INT(2)
  cmp %s $00 ; SEI = (S == 0)
  lds %d     ; S = D
  inx %s     ; S++
  jmne puts  ; IF (!SEI) PC = PUTS
  ret        ; RETURN

; Arguments:
; A - first string address
; B - second string address
; Returns:
; H - status
strcmp:
  lds %a
  ldg %b
  lodsb
  lodgb
  cmp %s %g
  jmne strcmp-fail
  cmp %s $00
  jme strcmp-eq
  inx %a
  inx %b
  jmp strcmp
strcmp-eq:
  ldh $00
  ret
strcmp-fail:
  ldh $01
  ret

; D - directory
; G - filename
; S - address to store data from a file
gfs-read-file:
  jmp fail

boot:
  lds st-msg
  call puts
  ; hlt
boot-start:
  ; Find the current CPU
  lds procchk-msg
  call puts
  ldd $00
  cpuid
  cmp %d $00
  jme boot-gc16x-cpu
  jmp boot-unk-cpu
boot-gc16x-cpu:
  lds proc-00-msg
  call puts
  jmp boot-shell
boot-unk-cpu:
  lds proc-unk-msg
  call puts
  jmp fail
boot-shell:
  ; Start the shell
  call com-mochaos

fail:
  lds fail-msg
  call puts
  hlt

com-mochaos:
  lds welcome-msg
  call puts
  jmp com-mochaos-goidaos
com-mochaos-prompt:
  lds env-PS
  call puts
com-mochaos-input:
  int $01    ; Get character from input
  cop %d     ; Save to D register
  push %d    ; Output the
  int $02    ; character
  lds comm
  ldg commi
  lodgb
  add %s %g
  storb %d
  inc commi
  cmp %d $7F ; Check for Backspace (1)
  jme com-mochaos-bs
  cmp %d $08 ; Check for Backspace (2)
  jme com-mochaos-bs
  cmp %d $04 ; Check for Ctrl-D (exit)
  jme com-mochaos-shutdown
  cmp %d $0A ; Check for Enter
  jmne com-mochaos-input
  jmp com-mochaos-process
com-mochaos-bs:
  lds commi
  lodsb
  cmp %s $00
  jme com-mochaos-bs-strict
com-mochaos-bs-strict:
  dec commi
  lds bs-smb
  call puts
  jmp com-mochaos-input
com-mochaos-process:
  ldd $00
  storb %d
  ; lds bad-inst-msg
  ; call puts
  lds comm
  call puts
  push $0A
  int $02
  lds commi
  ldd $00
  lodgb
  storb %d
  jmp com-mochaos-prompt
com-mochaaos-shutdown:
  lds exit-msg
  call puts
com-mochaos-term:
  push $00
  int $00

; Text
st-msg:       bytes "Loading MochaOS ...$^@"
fail-msg:     bytes "Fatal error$^@"
exit-msg:     bytes "$Shut down$^@"
welcome-msg:  bytes "Welcome to MochaOS!$To get help, type `help`$To shutdown, press Ctrl-D$$^@"

; CPU types
procchk-msg:  bytes "[0000] Checking CPU$^@"
proc-00-msg:  bytes "[0001] CPU: Mocha Core 16X$$^@"
proc-unk-msg: bytes "[0001] CPU: idk$$^@"

; Environment variables
env-PS:       bytes "^$ ^@^@^@^@^@^@^@^@^@"

; Control sequences
bs-smb:       bytes $08 $20 $08 "^@"

; Commands
full-inst-he: bytes "he^@"
bad-inst-msg: bytes "WTF???$^@"

comm:         bytes "^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@"
commi:        bytes $00

**Comment by xi816** [comment]
там ошибка должна сказать что именно покажи 5 строк выше самой ошибки от пытхона

**Comment by xi816** [comment]
нет
